In [1]:
Local varible and Global variable

SyntaxError: invalid syntax (578460201.py, line 1)

In [2]:
def fun():
    s= 'I love python'
    print(s)
fun()

I love python


In [3]:
def fun():
    s= 'I love python'
    print(s)
fun()
print(s)

I love python


NameError: name 's' is not defined

In [ ]:
Global variable

In [4]:
 s= 'I love python'
def fun():
    print(s)
fun()
print(s)

I love python
I love python


In [5]:
def fun():
    s = "Me too"
    print(s)
fun()
s='I love python'
print(s)

Me too
I love python


In [6]:
def fun():
    s += "Me too"
    print('inside',s)
fun()
s='I love python'
print('outside',s)

UnboundLocalError: cannot access local variable 's' where it is not associated with a value

In [7]:
def fun():
    global s
    s += 'Me too'
    print(s)
fun()
s='I love python'
print('outside',s)


I love pythonMe too
outside I love python


In [8]:
a =1

def f():
    print("inside the f()",a)

In [9]:
f()

inside the f() 1


In [13]:
def g():
    a=2
    print("inside the g()",a)

In [14]:
g()

inside the g() 2


In [15]:
def h():
    global a
    a=3
    print("inside the h()",a)

In [16]:
h()

inside the h() 3


In [17]:
a =1

def f():
    print("inside the f()",a)
def g():
    a=2
    print("inside the g()",a)
def h():
    global a
    a=3
    print("inside the h()",a)

In [18]:
print("global :",a)
f()
print("global :",a)
g()
print("global :",a)
h()

global : 1
inside the f() 1
global : 1
inside the g() 2
global : 1
inside the h() 3


In [30]:
a=1
def add1():
    b=2
    return a+b

add1()


3

1 2


In [21]:
a=1
b=2
def add():
    return a+b


In [22]:
add()

3

In [23]:
def add():
    a=1
    b=2
    return a+b

In [24]:
add()

3

<img src="diff_g%26L.png">

In [1]:
a=1
def f():
    b=2
    print(a+b)
f()
print(b)

3


NameError: name 'b' is not defined

In [2]:
f()
print(b)

3


NameError: name 'b' is not defined

In [35]:
##Deep copy and copy shallow 

In [37]:
list_1 =[1,2,3,4]
list_2 = list_1

In [38]:
print(list_1)
print(id(list_1))

[1, 2, 3, 4]
2414832141632


In [39]:
print(list_2)
print(id(list_2))

[1, 2, 3, 4]
2414832141632


In [40]:
list_1[2] = 9

In [41]:
list_1

[1, 2, 9, 4]

In [42]:
list_2

[1, 2, 9, 4]

In [44]:
#shallow copy
import copy
x= [1,2,3,4,5]
y=copy.copy(x)

In [47]:
id(y)

2414832355776

In [48]:
id(x)

2414832364736

In [49]:
x[2]=9

In [50]:
x

[1, 2, 9, 4, 5]

In [51]:
y

[1, 2, 3, 4, 5]

In [59]:
old_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
new_list = copy.copy(old_list)

In [60]:
old_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
new_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [55]:
old_list.append([2,3,5])

In [56]:
old_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 3, 5]]

In [57]:
new_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [62]:
old_list[1][1]='AA'

In [63]:
old_list

[[1, 2, 3], [4, 'AA', 6], [7, 8, 9]]

In [64]:
new_list

[[1, 2, 3], [4, 'AA', 6], [7, 8, 9]]

In [65]:
#deep copy
old_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
new_list = copy.deepcopy(old_list)

In [66]:
old_list.append([2,3,5])

In [67]:
old_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 3, 5]]

In [68]:
new_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [69]:
old_list[1][1]='AA'

In [70]:
old_list

[[1, 2, 3], [4, 'AA', 6], [7, 8, 9], [2, 3, 5]]

In [71]:
new_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

<img src="copy1.png">

In [96]:
#Deep copy

list1 = [[1,2,3],[2,3,4],[5,6,7]]

list2 = copy.deepcopy(list1)



In [97]:
list1.append([9,10,11])

In [98]:
list1

[[1, 2, 3], [2, 3, 4], [5, 6, 7], [9, 10, 11]]

In [99]:
id(list1)

2414832576576

In [100]:
list1[1][2]=89

In [93]:
list1

[[1, 2, 3], [2, 3, 4], [5, 6, 7], [9, 10, 11]]

In [95]:
list2

[[1, 2, 3], [2, 3, 4], [5, 6, 7]]

In [84]:
list3 = [[1,2,3],[2,3,4],[5,6,7]]

list4 = copy.copy(list1)

In [85]:
list3.append([9,10,11])

In [86]:
list3

[[1, 2, 3], [2, 3, 4], [5, 6, 7], [9, 10, 11]]

In [87]:
list4

[[1, 2, 3], [2, 3, 4], [5, 6, 7], [9, 10, 11]]

In [101]:
#Numpy

l = [1,1.8,'s']

In [102]:
!pip install numpy

In [ ]:
conda install -c anaconda numpy

In [103]:
import numpy

arr = numpy.array([1,2,3,4,5])



In [104]:
print(arr)

[1 2 3 4 5]


In [105]:
import numpy as np


arr = np.array([4,5,6,7,8])

In [106]:
arr

array([4, 5, 6, 7, 8])

In [107]:
np.__version__

'1.26.4'

In [108]:
type(arr)

numpy.ndarray

In [109]:
arr = np.array((4,5,6,7,8))

In [110]:
arr

array([4, 5, 6, 7, 8])

In [112]:
type(arr)

numpy.ndarray

In [113]:
#0-D array

arr1 = np.array(42)

In [114]:
arr1

array(42)

In [116]:
type(arr1)

numpy.ndarray

In [117]:
arr1.ndim

0

In [118]:
#1 - D array

arr2 = np.array([1,2,3,4,5])

In [119]:
arr2

array([1, 2, 3, 4, 5])

In [120]:
type(arr2)

numpy.ndarray

In [121]:
arr2.ndim

1

In [122]:
#2 D array

arr3 = np.array([[1,2,3],[4,5,6]])

In [125]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
type(arr3)

numpy.ndarray

In [124]:
arr3.ndim

2

In [127]:
arr3 = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [128]:
arr3.ndim

2

In [129]:
arr4= np.array([[[1,2],[3,4]],[[6,7],[8,9]]])

In [130]:
arr4

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [131]:
arr4.ndim

3

In [132]:
arr5= np.array([[[1,2],[3,4]],[[6,7],[8,9]],[[11,12],[13,14]]])

In [133]:
arr5.ndim

3

In [135]:
arr = np.array([[1,2,3,4],[5,6,7,8]],ndmin=5)

In [136]:
arr.ndim

5

In [137]:
arr

array([[[[[1, 2, 3, 4],
          [5, 6, 7, 8]]]]])

In [138]:
arr = np.array([1,2,3,4,5])

In [139]:
arr

array([1, 2, 3, 4, 5])

In [140]:
arr.ndim

1

In [141]:
arr[2]

3

In [150]:
arr1 = np.array([[1,2,3],[4,5,6],[2,3,9]])

In [151]:
arr1.ndim

2

In [152]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 9]])

In [144]:
arr1[1][1]

5

In [145]:
arr1[1,1]

5

In [149]:
2*3

6

In [154]:
arr1[2,1] + arr1[0,2]

6

In [155]:
arr1[2,2]

9

In [156]:
arr1[-1,-1]

9

In [157]:
arr1[-3,-2]

2

In [158]:
arr1[0,-2]

2

In [166]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],[[12,13,14],[17,18,19]]])

In [167]:
arr.ndim

3

In [168]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[12, 13, 14],
        [17, 18, 19]]])

In [169]:
arr[-1,-1,-1]

19

In [170]:
arr[-1,-2,-2]

13

In [172]:
arr[2,0,1]

13

In [173]:
arr1 = np.array([1,2,3,4,5])

In [174]:
arr1[1:4]

array([2, 3, 4])

In [175]:
arr1[4:]

array([5])

In [176]:
arr1[:3]

array([1, 2, 3])

In [177]:
arr1[1:3]

array([2, 3])

In [182]:
arr1[-2:-1]

array([4])

In [183]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [184]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [185]:
arr1[1,1:4]

array([7, 8, 9])

In [187]:
arr1[-1,-4:-1]

array([7, 8, 9])

In [188]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],[[12,13,14],[17,18,19]]])

In [189]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[12, 13, 14],
        [17, 18, 19]]])

In [208]:
arr[1:3,1:3,1:3]

array([[[11, 12]],

       [[18, 19]]])

In [209]:
arr[0:2,0,1]

array([2, 8])

In [194]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [195]:
arr1[0:2,2]

array([3, 8])

In [ ]:
data-- string, int,float,bool

In [ ]:
interger - i 
string - s
complex - c


In [ ]:
type()

In [3]:
dtype()

NameError: name 'dtype' is not defined

In [5]:
import numpy as np

arr = np.array([1,2,3,4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr1 = np.array(['banana','kiwi','apple'])

In [9]:
arr1.dtype

dtype('<U6')

In [ ]:
Unicode string - U

In [10]:
arr = np.array([1,2,3,4],dtype ='S')

In [11]:
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [12]:
arr.dtype

dtype('S1')

In [13]:
arr = np.array(['abcd','abcde','ab'])

In [14]:
arr.dtype

dtype('<U5')

In [22]:
arr = np.array([1,2,3],'i4')
print(arr)
print(arr.dtype)

[1 2 3]
int32


In [19]:
arr

array([1, 2, 3])

In [20]:
arr.dtype

dtype('int32')

In [23]:
arr = np.array([1,2,3],'S4')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3']
|S4


In [25]:
arr = np.array(['1','a',1,1.0],dtype = 'i')

ValueError: invalid literal for int() with base 10: 'a'

In [30]:
arr = np.array([1,2,3,4,5],dtype='S')

In [31]:
arr.dtype

dtype('S1')

In [32]:
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [ ]:
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string


In [33]:
arr = np.array([1.1,2.1,3.1])

In [34]:
arr.dtype

dtype('float64')

In [35]:
arr_n = arr.astype('i')

In [36]:
arr_n

array([1, 2, 3], dtype=int32)

In [37]:
arr1 = np.array([1,0,3,4,1])

In [38]:
arr1.dtype

dtype('int32')

In [45]:
arr2 = arr1.astype(bool)

In [46]:
arr2

array([ True, False,  True,  True,  True])

In [54]:
#copy and view

array1 = np.array([1,2,3,4,5])

array1_copy = array1.copy()


In [55]:
array1

array([1, 2, 3, 4, 5])

In [56]:
array1_copy

array([1, 2, 3, 4, 5])

In [57]:
array1[0] = 72

In [58]:
array1

array([72,  2,  3,  4,  5])

In [59]:
array1_copy

array([1, 2, 3, 4, 5])

In [60]:
array2 = np.array([1,2,3,4,5])

array2_view = array2.view()

In [61]:
array2

array([1, 2, 3, 4, 5])

In [62]:
array2_view

array([1, 2, 3, 4, 5])

In [63]:
array2[3]=89

In [64]:
array2

array([ 1,  2,  3, 89,  5])

In [65]:
array2_view

array([ 1,  2,  3, 89,  5])

In [66]:
arr = np.array([1,2,3,4,5])

In [67]:
x=arr.copy()


In [68]:
y=arr.view() 

In [70]:
print(x.base)

None


In [71]:
print(y.base)

[1 2 3 4 5]


In [72]:
#shape of the array
arr

array([1, 2, 3, 4, 5])

In [73]:
arr.shape

(5,)

In [74]:
arr1 =np.array([[1,2,3],[4,5,6]])

In [75]:
arr1.shape

(2, 3)

In [76]:
arr1 =np.array([[1,2,3,4],[4,5,6,7]])

In [77]:
arr1.shape

(2, 4)

In [122]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],ndmin=4)

In [123]:
arr2.shape

(1, 1, 4, 4)

In [124]:
arr2

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]]])

In [105]:
arr2

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]]])

In [106]:
arr1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [107]:
arr1.shape

(2, 4)

In [108]:
arr1.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [109]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [110]:
arr.shape

(12,)

In [111]:
arr1=arr.reshape(4,3)

In [112]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [114]:
arr2=arr.reshape(6,2)

In [115]:
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [116]:
arr3 = arr.reshape(2,6)

In [117]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [118]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [125]:
arr3=arr.reshape(2,2,3)

In [129]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [130]:
arr3.shape

(2, 2, 3)

In [131]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [132]:
arr.shape

(16,)

In [133]:
arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [134]:
arr.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

4X4X1

In [136]:
arr.reshape(4,4,1,1)

array([[[[ 1]],

        [[ 2]],

        [[ 3]],

        [[ 4]]],


       [[[ 5]],

        [[ 6]],

        [[ 7]],

        [[ 8]]],


       [[[ 9]],

        [[10]],

        [[11]],

        [[12]]],


       [[[13]],

        [[14]],

        [[15]],

        [[16]]]])

In [140]:
arr1=arr.reshape(2,2,2,2) 

In [141]:
arr1

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [142]:
arr1.shape

(2, 2, 2, 2)

In [143]:
arr1.ndim

4

In [156]:
arr = np.array([[[[1,2,3,4]],[[2,3,4,5]],[[6,7,8,9]]]])

In [157]:
arr.shape

(1, 3, 1, 4)

In [154]:
arr.ndim

3

In [158]:
array1 = np.array([1,2,3,4,5,6,7,8])

In [160]:
arr=array1.reshape(4,2).base

In [161]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [162]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [163]:
arr.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [164]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
#iteration of list

array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [166]:
for i in array1:
    print(i)

1
2
3
4
5
6
7
8


In [167]:
array2=np.array([[1,2,3],[4,5,6]])

In [171]:
for i in array2:
    for j in i:
        print(j)
    
    

1
2
3
4
5
6


In [172]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [173]:
for i in np.nditer(array2):
    print(i)
    

1
2
3
4
5
6


In [174]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [176]:
search = np.where(array2 == 5)

In [178]:
search

(array([1], dtype=int64), array([1], dtype=int64))

In [179]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [180]:
even = np.where(array1%2==0)

In [181]:
even

(array([1, 3, 5, 7], dtype=int64),)

In [183]:
odd = np.where(array1%2!=0)

In [184]:
odd

(array([0, 2, 4, 6], dtype=int64),)

In [185]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [186]:
x=np.searchsorted(arr,5)

In [187]:
x

4

In [188]:
x=np.searchsorted(arr,[3,6,8])

In [189]:
x

array([2, 5, 7], dtype=int64)

In [190]:
arr = np.array([6,1,23,90])

In [198]:
np.sort(arr)

array([ 1,  6, 23, 90])

In [199]:
arr1 = np.array(['prachi','vinay','vaibhav','rashi'])

In [200]:
np.sort(arr1)

array(['prachi', 'rashi', 'vaibhav', 'vinay'], dtype='<U7')

In [207]:
arr1[::-1].sort()

None


In [202]:
arr = np.array([31,32,33,34])

In [208]:
x=[True,False,True,True]

In [209]:
arr1=arr[x]

In [210]:
arr1

array([31, 33, 34])

In [211]:
#Numpy broadcasting

arr1 =np.array([1,2,3])
arr2 = np.array([[1],[2],[3]])

In [212]:
arr1 + arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [217]:
arr1 =np.array([1,2,3])

n= 5



In [218]:
arr1*n

array([ 5, 10, 15])

In [214]:
arr1 + n

array([6, 7, 8])

In [219]:
arr1 =np.array([1,2,3])
arr2=np.array([4,5,6])

In [216]:
arr1 +arr2

array([5, 7, 9])

In [220]:
arr1*arr2

array([ 4, 10, 18])

In [227]:
arr2 = np.array([[1,5],[2,9],[3,8]])
n=5

In [226]:
arr2+n

array([[ 6, 10],
       [ 7, 14],
       [ 8, 13]])

In [239]:
from numpy import random

x = random.randint(5)
print(x)

1


In [230]:
x

0

In [242]:
from numpy import random

x = random.rand(100)
print(x)

[0.97559847 0.53477148 0.23595941 0.98180415 0.40415772 0.83960111
 0.96018693 0.76145839 0.17529625 0.93125565 0.58400371 0.24956618
 0.64149035 0.33724857 0.55018095 0.69781697 0.41175269 0.81040676
 0.46877331 0.36821268 0.60648495 0.15370068 0.0373463  0.12316481
 0.59452611 0.72868539 0.06270032 0.65952778 0.1978498  0.63815934
 0.50439185 0.77847099 0.53313786 0.04884355 0.83806205 0.4762032
 0.96109924 0.98606467 0.288498   0.4336827  0.25399267 0.82202062
 0.4057322  0.84040548 0.78635611 0.02385466 0.1666559  0.22182037
 0.56436645 0.09139435 0.21024649 0.40349302 0.99471557 0.38726381
 0.32925709 0.54561565 0.20575541 0.70422034 0.89299003 0.80606991
 0.79875479 0.40544048 0.20415055 0.35243262 0.01005418 0.47199313
 0.79742982 0.40705329 0.94517665 0.89563286 0.64263491 0.34664391
 0.38399798 0.63374225 0.05606757 0.89605225 0.03050109 0.82737693
 0.70009683 0.09312027 0.99019345 0.54342626 0.9614906  0.95069823
 0.08441179 0.07255377 0.38230991 0.66039404 0.06979415 0.44737